# Generated by Django 5.0.1 on 2024-02-22 21:38

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('firstName', models.TextField(max_length=20)),
                ('lastName', models.TextField(max_length=20)),
                ('username', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('streamNames', models.TextField(max_length=10000)),
                ('password', models.CharField(max_length=1000)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('subscription', models.IntegerField(default=3)),
                ('streamID', models.TextField(default='null')),
                ('active_models', multiselectfield.db.fields.MultiSelectField(choices=[('human', 'human'), ('fire', 'fire'), ('weapon', 'weapon'), ('numberplate', 'numberplate')], default=None, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('name', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cuser')),
            ],
        ),
    ]
