# Generated by Django 5.0.1 on 2024-02-22 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_track_id_alter_track_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='streamNames',
        ),
    ]
