# Generated by Django 5.0.1 on 2024-02-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='track',
        ),
    ]
