# Generated by Django 5.0.1 on 2024-02-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_detection_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='type',
        ),
    ]
