# Generated by Django 5.0.1 on 2024-02-23 09:19

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_detection_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('human', 'human'), ('fire', 'fire'), ('weapon', 'weapon'), ('numberplate', 'numberplate')], default=None, max_length=2048),
        ),
    ]
